"""Add foreign keys and relationship fixes

Revision ID: 6806727ce9fc
Revises: 
Create Date: 2026-03-12 21:10:14.061842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6806727ce9fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_table('audit_reports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_reports_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_reports_pkey'))
    )
    op.create_index(op.f('audit_reports_status_idx'), 'audit_reports', ['status'], unique=False)
    op.create_index(op.f('audit_reports_user_id_idx'), 'audit_reports', ['user_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mask', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bank_accounts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bank_accounts_pkey'))
    )
    op.create_index(op.f('bank_accounts_user_id_idx'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], name=op.f('transactions_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('transactions_account_id_idx'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('transactions_date_idx'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('transactions_external_id_idx'), 'transactions', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('transactions_external_id_idx'), table_name='transactions')
    op.drop_index(op.f('transactions_date_idx'), table_name='transactions')
    op.drop_index(op.f('transactions_account_id_idx'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('bank_accounts_user_id_idx'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('audit_reports_user_id_idx'), table_name='audit_reports')
    op.drop_index(op.f('audit_reports_status_idx'), table_name='audit_reports')
    op.drop_table('audit_reports')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
