import uuid
from typing import Any, List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert

from src.api import deps, schemas
from src.core.repository import BaseRepository
from src.models.core import Transaction, BankAccount

router = APIRouter()
account_repo = BaseRepository(BankAccount)

@router.post("/ingest", response_model=List[schemas.TransactionResponse], status_code=status.HTTP_200_OK)
async def ingest_transactions(
    *,
    db: AsyncSession = Depends(deps.get_db),
    payload: schemas.IngestTransactionsRequest,
) -> Any:
    """
    Idempotent transaction ingestion.
    Uses PostgreSQL UPSERT (ON CONFLICT DO UPDATE) to ensure identical external_ids 
    do not create duplicate rows if ingested multiple times.
    """
    account = await account_repo.get(db=db, id=payload.account_id)
    if not account:
        raise HTTPException(status_code=404, detail="Account not found")

    if not payload.transactions:
        return []

    # Prepare values for bulk UPSERT
    values_to_insert = []
    for txn in payload.transactions:
        dump = txn.model_dump()
        dump["account_id"] = payload.account_id
        # Convert date to string for our simple model (in reality we'd use native Date)
        dump["date"] = dump["date"].isoformat()
        # id is autogenerated by the DB for new rows, but we need to supply it if we want to return it easily
        # For simplicity in this demo, we'll let SQLAlchemy handle it if new, but UPSERT is tricky with ORM returning.
        dump["id"] = uuid.uuid4() 
        values_to_insert.append(dump)

    # Build the PostgreSQL specific ON CONFLICT statement
    stmt = insert(Transaction).values(values_to_insert)
    
    # If the external_id already exists, update the other fields (idempotent)
    update_dict = {
        "amount": stmt.excluded.amount,
        "merchant_name": stmt.excluded.merchant_name,
        "description": stmt.excluded.description,
    }
    
    stmt = stmt.on_conflict_do_update(
        index_elements=["external_id"],
        set_=update_dict
    ).returning(Transaction)

    result = await db.execute(stmt)
    await db.commit()
    
    upserted_transactions = result.scalars().all()
    return upserted_transactions
